# Test 1, Question 56
> **Hint:** In Databricks, import code for all questions via this URL:
> 
> https://github.com/flrs/spark_practice_tests_code/raw/main/spark_practice_tests_code.dbc

In [0]:
%run ./create_itemsDf2

## Answer 1 (correct)

In [0]:
itemsDf.createOrReplaceTempView("itemsDf")
spark.sql("SELECT supplier, explode(attributes) FROM itemsDf").show()

+-------------------+-------+
|           supplier|    col|
+-------------------+-------+
|Sports Company Inc.|   blue|
|Sports Company Inc.| winter|
|Sports Company Inc.|   cozy|
|              YetiX|    red|
|              YetiX| summer|
|              YetiX|  fresh|
|              YetiX|cooling|
|Sports Company Inc.|  green|
|Sports Company Inc.| summer|
|Sports Company Inc.| travel|
+-------------------+-------+

## Answer 2 (incorrect)

In [0]:
itemsDf.createOrReplaceView("itemsDf")
spark.sql("SELECT supplier, explode(attributes) FROM itemsDf").show()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-2667665041566815> in <module>
----> 1 itemsDf.createOrReplaceView("itemsDf")
      2 spark.sql("SELECT supplier, explode(attributes) FROM itemsDf").show()

/databricks/spark/python/pyspark/sql/dataframe.py in __getattr__(self, name)
   1664         """
   1665         if name not in self.columns:
-> 1666             raise AttributeError(
   1667                 "'%s' object has no attribute '%s'" % (self.__class__.__name__, name))
   1668         jc = self._jdf.apply(name)

AttributeError: 'DataFrame' object has no attribute 'createOrReplaceView'

## Answer 3 (incorrect)

In [0]:
spark.sql("SELECT 'supplier', explode('Attributes') FROM itemsDf")

---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
<command-2667665041566817> in <module>
----> 1 spark.sql("SELECT 'supplier', explode('Attributes') FROM itemsDf")

/databricks/spark/python/pyspark/sql/session.py in sql(self, sqlQuery)
    775         [Row(f1=1, f2='row1'), Row(f1=2, f2='row2'), Row(f1=3, f2='row3')]
    776         """
--> 777         return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
    778
    779     def table(self, tableName):

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    121                 # Hide where the exception came from that shows a non-Pythonic
    122                 # JVM exception message.
--> 123                 raise converted from None
    124             else:
    125                 raise

AnalysisException: cannot resolve 'explode('Attributes')' due to data type mismatch: input to function explode should be array or map type, not string; line 1 pos 19;
'Project [supplier AS supplier#61, unresolvedalias(explode(Attributes), None)]
+- SubqueryAlias itemsdf
   +- LogicalRDD [itemId#6, itemName#7, attributes#8, supplier#9], false

## Answer 4 (incorrect)

In [0]:
itemsDf.createOrReplaceTempView("itemsDf")
spark.sql("SELECT 'supplier', explode('Attributes') FROM itemsDf").show()

---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
<command-2667665041566819> in <module>
      1 itemsDf.createOrReplaceTempView("itemsDf")
----> 2 spark.sql("SELECT 'supplier', explode('Attributes') FROM itemsDf").show()

/databricks/spark/python/pyspark/sql/session.py in sql(self, sqlQuery)
    775         [Row(f1=1, f2='row1'), Row(f1=2, f2='row2'), Row(f1=3, f2='row3')]
    776         """
--> 777         return DataFrame(self._jsparkSession.sql(sqlQuery), self._wrapped)
    778
    779     def table(self, tableName):

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    121                 # Hide where the exception came from that shows a non-Pythonic
    122                 # JVM exception message.
--> 123                 raise converted from None
    124             else:
    125                 raise

AnalysisException: cannot resolve 'explode('Attributes')' due to data type mismatch: input to function explode should be array or map type, not string; line 1 pos 19;
'Project [supplier AS supplier#62, unresolvedalias(explode(Attributes), None)]
+- SubqueryAlias itemsdf
   +- LogicalRDD [itemId#6, itemName#7, attributes#8, supplier#9], false

## Answer 5 (incorrect)

In [0]:
itemsDf.createOrReplaceView("itemsDf")
spark.sql("SELECT 'supplier', explode('Attributes') FROM itemsDf").show()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-2667665041566821> in <module>
----> 1 itemsDf.createOrReplaceView("itemsDf")
      2 spark.sql("SELECT 'supplier', explode('Attributes') FROM itemsDf").show()

/databricks/spark/python/pyspark/sql/dataframe.py in __getattr__(self, name)
   1664         """
   1665         if name not in self.columns:
-> 1666             raise AttributeError(
   1667                 "'%s' object has no attribute '%s'" % (self.__class__.__name__, name))
   1668         jc = self._jdf.apply(name)

AttributeError: 'DataFrame' object has no attribute 'createOrReplaceView'